blank_issues_enabled: false
contact_links:
  - name: Create a suggestion instead
    url: https://github.com/terranova3/hl2rp-suggestions/issues
    about: Not a bug? Suggest sometihng to be added to the server in here.
